### ISSUE TITLE
Crash if listing empty store.

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/SuperGrate#37]
**Describe the bug**
SG Crashes if listing empty store.

**To Reproduce**
Open fresh Super Grate install. Click on "List Store"

**Logs**
```
[INFO]<10:11:15 PM> Generating SuperGrate.xml...
[SUCCESS]<10:11:15 PM> Saved.
[SUCCESS]<10:11:15 PM> Config loaded!
[SUCCESS]<10:11:15 PM> Welcome to prerelease - Super Grate! v1.3.0.0
[INFO]<10:11:15 PM> Enter some information to get started!
[INFO]<10:11:17 PM> Listing users from store: .\STORE...
[ERROR]<10:11:17 PM> Could not find a part of the path 'C:\Users\dylan\Desktop\STORE'.
[VERBOSE]<10:11:17 PM> ERROR
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
   at SuperGrate.Misc.<>c.<<GetUsersFromStore>b__11_0>d.MoveNext()
[ERROR]<10:11:17 PM> Failed to list users from store.
[ERROR]<10:11:17 PM> 
-----------FATAL ERROR-----------

[ERROR]<10:11:17 PM> Object reference not set to an instance of an object.

[ERROR]<10:11:17 PM> 
--------------TRACE--------------

[ERROR]<10:11:17 PM>    at SuperGrate.UserList.ULControl.SetRows(ListView Owner, UserRows Rows, ULColumnType SortColumn, ULSortDirection SortDirection)
   at SuperGrate.Main.<BtnListStore_Click>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by krisdb2009** [comment]
Fixed in: cf1b990
