### ISSUE TITLE
Source Computer User Delete

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/SuperGrate#38]
**Describe the bug**
Deleting a user fails when trying to list.

**To Reproduce**
Delete a user from a remote source.

**Logs**
```
[INFO]<9:14:14 AM> Sending Profile Delete Daemon...
[INFO]<9:14:14 AM> Deleting 'CP-PC-VM1\Administrator' from cp-pc-vm1...
[VERBOSE]<9:14:14 AM> Waiting for SuperGratePD to finish...
[INFO]<9:14:18 AM> Removing Daemon...
[SUCCESS]<9:14:18 AM> Done.
[INFO]<9:14:18 AM> Getting list of users on: cp-pc-vm1...
[INFO]<9:14:18 AM> Listing users was canceled.
[ERROR]<9:14:18 AM> 
-----------FATAL ERROR-----------

[ERROR]<9:14:18 AM> Object reference not set to an instance of an object.

[ERROR]<9:14:18 AM> 
--------------TRACE--------------

[ERROR]<9:14:18 AM>    at SuperGrate.UserList.ULControl.SetRows(ListView Owner, UserRows Rows, ULColumnType SortColumn, ULSortDirection SortDirection)
   at SuperGrate.Main.<BtnListSource_Click>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

**Comment by krisdb2009** [comment]
Duplicate of #34
