### ISSUE TITLE
Full-migrations not working correctly.

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/SuperGrate#42]
**Describe the bug**
A source to destination "in one step" migration is not working right.

**To Reproduce**
Enter Source & Destination, click "List Source", select a user, click "Start".

**Expected behavior**
A migration of the user from source to destination.

**Screenshots**
![image](https://user-images.githubusercontent.com/8226974/73231071-47bbd200-414d-11ea-91ac-8d3eac844871.png)

**Logs**
```
[SUCCESS]<9:35:41 PM> USMT Finished.
[INFO]<9:35:44 PM> Uploading user state to the Store...
[SUCCESS]<9:35:45 PM> User state successfully uploaded.
[INFO]<9:35:45 PM> Removing USMT from: BA-DYLANPC...
[SUCCESS]<9:35:45 PM> USMT removed successfully.
[INFO]<9:35:45 PM> Reading OS Architecture...
[INFO]<9:35:45 PM> OS Architecture is: 64-bit.
[INFO]<9:35:45 PM> Uploading USMT to: BA-DYLANPC
[SUCCESS]<9:35:45 PM> USMT uploaded successfully.
[INFO]<9:35:45 PM> Applying user state: 'BELOWAVERAGE\kevin' on 'BA-DYLANPC'...
[INFO]<9:35:45 PM> Downloading user state to: BA-DYLANPC...
[ERROR]<9:35:45 PM> Could not find file '.\STORE\S-1-5-21-823193273-4233245511-2126334244-1149\data'.
[VERBOSE]<9:35:45 PM> ERROR
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at SuperGrate.FileOperations.CopyFile(String Source, String Destination) in C:\Users\dylan\source\repos\SuperGrate\SuperGrate\Classes\FileOperations.cs:line 17
   at SuperGrate.USMT.<>c__DisplayClass16_0.<DownloadFromStore>b__0() in C:\Users\dylan\source\repos\SuperGrate\SuperGrate\Classes\USMT.cs:line 247
[ERROR]<9:35:45 PM> Failed to download state data to: BA-DYLANPC.
[ERROR]<9:35:45 PM> Failed to get SID from store ID: S-1-5-21-823193273-4233245511-2126334244-1149
[INFO]<9:35:45 PM> Removing USMT from: BA-DYLANPC...
[SUCCESS]<9:35:45 PM> USMT removed successfully.
[INFO]<9:35:45 PM> Done.
```

**Additional context**
Super Grate is looking for the stored user by SID, instead of by "Store GUID".

**Comment by krisdb2009** [comment]
Issue is because in version 1.2.0.0, Super Grate would keep track of the store by SID, now it keeps track via GUID. This method needs updated to find the user in the store by GUID instead of SID.

**Comment by zm1868179** [comment]
Hi Dylan long time no see. I believe I might can help with this bug I’ll download the source and do some debug and submit a pr
